chore: add utils package

diff --git a/.github/workflows/api-release.yml b/.github/workflows/api-release.yml
--- a/.github/workflows/api-release.yml
+++ b/.github/workflows/api-release.yml
@@ -1,4 +1,4 @@
-name: API Publish
+name: TypeScript Package Publish
 
 on:
   push:
@@ -15,7 +15,7 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  publish:
+  publish-api:
     runs-on: depot-ubuntu-24.04
     defaults:
       run:
@@ -52,4 +52,47 @@ jobs:
         with:
           token: ${{ secrets.NPM_TOKEN }}
           package: ./src/typescript/api
+
+  publish-utils:
+    needs: publish-api
+    runs-on: depot-ubuntu-24.04
+    defaults:
+      run:
+        working-directory: ./src/typescript/utils
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 22
+          registry-url: https://registry.npmjs.org
+
+      - name: Set version from tag
+        run: |
+          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
+            TAG_NAME=${{ github.event.inputs.tag }}
+          else
+            TAG_NAME=${GITHUB_REF_NAME}
+          fi
+
+          if [ -z "$TAG_NAME" ]; then
+            echo "Error: No tag specified."
+            exit 1
+          fi
+
+          npm version "$TAG_NAME" --no-git-tag-version
+
+      - name: Install API dependencies
+        run: npm --prefix ../api ci
+      - name: Build API dependency
+        run: npm --prefix ../api run build
+      - name: Install dependencies
+        run: npm ci
+      - name: Build package
+        run: npm run build
+      - uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c
+        with:
+          token: ${{ secrets.NPM_TOKEN }}
+          package: ./src/typescript/utils
 
